In [5]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個

array([50, 60, 70, 80, 90])

In [8]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 63,  58,  97,  91,  60],
       [ 89,  99,  69,  99,  81],
       [ 78,  51,  53,  69,  59],
       [ 58,  68,  97,  89,  83],
       [ 52,  50,  92,  88,  94],
       [ 55,  84,  74,  66,  94],
       [ 80,  97,  53,  79,  74],
       [ 60,  59,  73,  74,  75],
       [ 53,  72,  54,  79,  50],
       [ 66,  83,  55,  84,  74],
       [ 70,  94,  52,  83,  53],
       [ 65,  94,  96,  87,  53],
       [ 97,  84,  58,  93,  59],
       [ 61,  92,  83,  87,  76],
       [ 54,  97,  59,  73,  50],
       [ 60,  61,  71,  50,  50],
       [ 91,  74,  66,  90,  74],
       [ 67,  81,  85,  85,  70],
       [ 89,  76,  78,  88,  50],
       [ 50,  89,  67,  85,  66],
       [ 52,  66,  94,  56,  53],
       [ 92,  84,  56,  58,  88],
       [ 79,  94,  79,  97,  92],
       [ 66,  60,  70,  83,  94],
       [ 84,  56,  83,  93,  75],
       [ 58,  56,  89,  93,  51],
       [ 94,  77,  63,  81,  65],
       [ 83,  73,  66,  66,  62],
       [ 91,  60,  85,  91,  81],
       [ 73,  

In [14]:
#第一位學生的分數
scores[0]
scores[0, :]
scores[:1,]

array([[63, 58, 97, 91, 60]], dtype=int32)

In [ ]:
#前5位學生,前3個分數
scores[:5,]
scores[:5,:3]

array([[63, 58, 97],
       [89, 99, 69],
       [78, 51, 53],
       [58, 68, 97],
       [52, 50, 92]], dtype=int32)

In [17]:
#第1科分數
scores[:,0]

array([ 63,  89,  78,  58,  52,  55,  80,  60,  53,  66,  70,  65,  97,
        61,  54,  60,  91,  67,  89,  50,  52,  92,  79,  66,  84,  58,
        94,  83,  91,  73,  94,  85,  86,  53,  82,  86,  53,  95,  79,
        68, 100,  69,  67,  91,  83,  68,  92,  72,  65,  58], dtype=int32)

In [18]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([369, 437, 310, 395, 376, 373, 383, 341, 308, 362, 352, 395, 391,
       399, 333, 292, 395, 388, 381, 357, 321, 378, 441, 373, 391, 347,
       380, 350, 408, 377, 432, 385, 409, 379, 382, 386, 335, 456, 372,
       368, 380, 353, 368, 434, 364, 359, 379, 336, 319, 357], dtype=int32)

In [19]:
total / 5

array([73.8, 87.4, 62. , 79. , 75.2, 74.6, 76.6, 68.2, 61.6, 72.4, 70.4,
       79. , 78.2, 79.8, 66.6, 58.4, 79. , 77.6, 76.2, 71.4, 64.2, 75.6,
       88.2, 74.6, 78.2, 69.4, 76. , 70. , 81.6, 75.4, 86.4, 77. , 81.8,
       75.8, 76.4, 77.2, 67. , 91.2, 74.4, 73.6, 76. , 70.6, 73.6, 86.8,
       72.8, 71.8, 75.8, 67.2, 63.8, 71.4])

In [ ]:
#np裡面的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([73.8, 87.4, 62. , 79. , 75.2, 74.6, 76.6, 68.2, 61.6, 72.4, 70.4,
       79. , 78.2, 79.8, 66.6, 58.4, 79. , 77.6, 76.2, 71.4, 64.2, 75.6,
       88.2, 74.6, 78.2, 69.4, 76. , 70. , 81.6, 75.4, 86.4, 77. , 81.8,
       75.8, 76.4, 77.2, 67. , 91.2, 74.4, 73.6, 76. , 70.6, 73.6, 86.8,
       72.8, 71.8, 75.8, 67.2, 63.8, 71.4])

In [22]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([73.8, 87.4, 62. , 79. , 75.2, 74.6, 76.6, 68.2, 61.6, 72.4, 70.4,
       79. , 78.2, 79.8, 66.6, 58.4, 79. , 77.6, 76.2, 71.4, 64.2, 75.6,
       88.2, 74.6, 78.2, 69.4, 76. , 70. , 81.6, 75.4, 86.4, 77. , 81.8,
       75.8, 76.4, 77.2, 67. , 91.2, 74.4, 73.6, 76. , 70.6, 73.6, 86.8,
       72.8, 71.8, 75.8, 67.2, 63.8, 71.4])