In [14]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個

array([50, 60, 70, 80, 90])

In [16]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 75,  59,  91,  92,  75],
       [ 69,  84,  55,  79,  77],
       [ 52,  68,  58,  82,  93],
       [ 57,  61,  95,  87,  80],
       [ 89,  94,  58,  91,  88],
       [ 75,  88,  93,  62,  54],
       [ 83, 100,  51,  50,  55],
       [ 71,  67,  61,  64,  72],
       [ 55,  86,  92,  97,  92],
       [ 97,  72,  97,  69,  66],
       [ 80,  59, 100,  50,  75],
       [ 94, 100,  65,  79,  62],
       [ 79,  52,  82,  89,  62],
       [ 85,  56,  78,  66,  67],
       [ 68,  57,  71, 100,  51],
       [ 90,  95,  92,  72,  82],
       [ 88,  94,  85,  56,  75],
       [ 96,  86,  71,  62,  56],
       [ 78,  57,  99,  81,  53],
       [ 57,  89,  85,  59,  59],
       [ 59,  82,  80,  72,  79],
       [ 69,  59,  94,  77,  71],
       [ 86,  80,  52,  52,  82],
       [ 88,  89,  94,  89,  80],
       [ 86,  91,  53,  51,  90],
       [ 94,  89,  88,  94,  72],
       [ 89,  76,  60,  72,  55],
       [ 54,  61,  61,  60,  52],
       [ 96,  66,  54,  54,  74],
       [ 54,  

In [19]:
#第一位學生的分數
scores1 = scores[0]
print(scores1.ndim, scores1.shape)
scores2 = scores[0:2, :]
print(scores2.ndim, scores2.shape)
scores[:1,]

1 (5,)
2 (2, 5)


array([[75, 59, 91, 92, 75]], dtype=int32)

In [ ]:
#前5位學生,前3個分數
scores[:5,]
scores[:5,:3]

array([[63, 58, 97],
       [89, 99, 69],
       [78, 51, 53],
       [58, 68, 97],
       [52, 50, 92]], dtype=int32)

In [ ]:
#第1科分數
scores[:,0]

array([ 63,  89,  78,  58,  52,  55,  80,  60,  53,  66,  70,  65,  97,
        61,  54,  60,  91,  67,  89,  50,  52,  92,  79,  66,  84,  58,
        94,  83,  91,  73,  94,  85,  86,  53,  82,  86,  53,  95,  79,
        68, 100,  69,  67,  91,  83,  68,  92,  72,  65,  58], dtype=int32)

In [ ]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([369, 437, 310, 395, 376, 373, 383, 341, 308, 362, 352, 395, 391,
       399, 333, 292, 395, 388, 381, 357, 321, 378, 441, 373, 391, 347,
       380, 350, 408, 377, 432, 385, 409, 379, 382, 386, 335, 456, 372,
       368, 380, 353, 368, 434, 364, 359, 379, 336, 319, 357], dtype=int32)

In [ ]:
total / 5

array([73.8, 87.4, 62. , 79. , 75.2, 74.6, 76.6, 68.2, 61.6, 72.4, 70.4,
       79. , 78.2, 79.8, 66.6, 58.4, 79. , 77.6, 76.2, 71.4, 64.2, 75.6,
       88.2, 74.6, 78.2, 69.4, 76. , 70. , 81.6, 75.4, 86.4, 77. , 81.8,
       75.8, 76.4, 77.2, 67. , 91.2, 74.4, 73.6, 76. , 70.6, 73.6, 86.8,
       72.8, 71.8, 75.8, 67.2, 63.8, 71.4])

In [ ]:
#np裡面的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([73.8, 87.4, 62. , 79. , 75.2, 74.6, 76.6, 68.2, 61.6, 72.4, 70.4,
       79. , 78.2, 79.8, 66.6, 58.4, 79. , 77.6, 76.2, 71.4, 64.2, 75.6,
       88.2, 74.6, 78.2, 69.4, 76. , 70. , 81.6, 75.4, 86.4, 77. , 81.8,
       75.8, 76.4, 77.2, 67. , 91.2, 74.4, 73.6, 76. , 70.6, 73.6, 86.8,
       72.8, 71.8, 75.8, 67.2, 63.8, 71.4])

In [ ]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([73.8, 87.4, 62. , 79. , 75.2, 74.6, 76.6, 68.2, 61.6, 72.4, 70.4,
       79. , 78.2, 79.8, 66.6, 58.4, 79. , 77.6, 76.2, 71.4, 64.2, 75.6,
       88.2, 74.6, 78.2, 69.4, 76. , 70. , 81.6, 75.4, 86.4, 77. , 81.8,
       75.8, 76.4, 77.2, 67. , 91.2, 74.4, 73.6, 76. , 70.6, 73.6, 86.8,
       72.8, 71.8, 75.8, 67.2, 63.8, 71.4])