In [1]:
import numpy as np

a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [ ]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [ ]:
#二維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #返回一个表示数组每个维度大小的元组。比如，二维数组 shape 可能是 (3, 4)，表示 3 行 4 列。
arr.size #数组中所有元素的总数，相当于 shape 中各维度大小的乘积。
arr.dtype #表示数组中元素的数据类型，如 int32、float64 等。


dtype('int64')

In [8]:
np.random.rand(3,4)

array([[0.49197139, 0.98193242, 0.2222256 , 0.49146397],
       [0.98893208, 0.77584251, 0.12933128, 0.82481087],
       [0.53751159, 0.97208221, 0.87265912, 0.07596581]])

In [11]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 96,  93,  96,  60,  89],
       [ 65,  78,  71,  85,  55],
       [ 89,  87,  56,  59,  84],
       [ 89,  55,  83,  60,  55],
       [ 98,  67,  51,  60,  92],
       [ 83,  75,  71,  64,  63],
       [ 62,  61,  80,  58,  93],
       [ 66,  62,  93,  77,  96],
       [ 71,  80,  78,  99,  58],
       [ 92,  68,  75,  97,  87],
       [ 95,  80,  67,  60,  80],
       [ 71,  82,  59,  63,  81],
       [ 64,  81,  86,  51,  54],
       [ 89,  96,  71,  76,  71],
       [ 74,  62,  70,  90,  79],
       [ 88,  75,  51,  60,  61],
       [ 67,  76,  90,  53,  85],
       [ 93,  83,  64,  92,  99],
       [ 54, 100,  80,  75,  51],
       [ 95,  74,  90,  82,  53],
       [ 93,  68,  89,  70,  69],
       [ 54,  63,  89,  81,  68],
       [ 65,  57,  89,  52,  53],
       [ 51,  81,  73,  81,  78],
       [ 70,  73,  70, 100,  98],
       [ 92,  86,  60,  80,  97],
       [ 88,  75,  61,  69,  74],
       [ 92,  75,  54,  97,  54],
       [100,  93,  81,  78,  87],
       [ 79,  